export const CurrencyList = [
    { currency: 'US Dollar', ISO: 'USD',symbol: '$' },
    { currency: 'Euro', ISO: 'EUR',symbol: '€' },
    { currency: 'Russian Ruble', ISO: 'RUB',symbol: '₽' },
    { currency: 'Argentine Peso', ISO: 'ARS',symbol: '$' },
    { currency: 'Armenian Dram', ISO: 'AMD',symbol: '֏' },
    { currency: 'Australian Dollar', ISO: 'AUD',symbol: '$' },
    { currency: 'Azerbaijani Manat', ISO: 'AZN',symbol: '₼' },
    { currency: 'Bangladeshi Taka', ISO: 'BDT',symbol: '৳' },
    { currency: 'Belarusian Ruble', ISO: 'BYN',symbol: 'Br' },
    { currency: 'Indian Rupee', ISO: 'INR',symbol: '₹' },
    { currency: 'Bolivian Boliviano', ISO: 'BOB',symbol: 'Bs' },
    { currency: 'Brazilian Real', ISO: 'BRL',symbol: 'R$' },
    { currency: 'Singapore Dollar', ISO: 'SGD',symbol: '$' },
    { currency: 'Burundian Franc', ISO: 'BIF',symbol: 'FBu' },
    { currency: 'Cambodian Riel', ISO: 'KHR',symbol: '៛' },
    { currency: 'Canadian Dollar', ISO: 'CAD',symbol: '$' },
    { currency: 'Chilean Peso', ISO: 'CLP',symbol: '$' },
    { currency: 'Renminbi', ISO: 'CNY',symbol: '¥' },
    { currency: 'Colombian Peso', ISO: 'COP',symbol: '$' },
    { currency: 'Congolese Franc', ISO: 'CDF',symbol: 'FC' },
    { currency: 'New Zealand Dollar', ISO: 'NZD',symbol: '$' },
    { currency: 'Costa Rican Colón', ISO: 'CRC',symbol: '₡' },
    { currency: 'Czech Koruna', ISO: 'CZK',symbol: 'Kč' },
    { currency: 'Dominican Peso', ISO: 'DOP',symbol: '$' },
    { currency: 'Egyptian Pound', ISO: 'EGP',symbol: 'LE' },
    { currency: 'South African Rand', ISO: 'ZAR',symbol: 'R' },
    { currency: 'Ethiopian Birr', ISO: 'ETB',symbol: 'Br' },
    { currency: 'Fijian Dollar', ISO: 'FJD',symbol: 'FJ$' },
    { currency: 'Gambian Dalasi', ISO: 'GMD',symbol: 'D' },
    { currency: 'Georgian Lari', ISO: 'GEL',symbol: '₾' },
    { currency: 'Ghanaian Cedi', ISO: 'GHS',symbol: 'GH₵' },
    { currency: 'Guatemalan Quetzal', ISO: 'GTQ',symbol: 'Q' },
    { currency: 'Guinean Franc', ISO: 'GNF',symbol: 'FG' },
    { currency: 'Guyanese Dollar', ISO: 'GYD',symbol: '$' },
    { currency: 'Haitian Gourde', ISO: 'HTG',symbol: 'G' },
    { currency: 'Honduran Lempira', ISO: 'HNL',symbol: 'L' },
    { currency: 'Hong Kong Dollar', ISO: 'HKD',symbol: '$' },
    { currency: 'Hungarian Forint', ISO: 'HUF',symbol: 'Ft' },
    { currency: 'Icelandic Króna', ISO: 'ISK',symbol: 'kr' },
    { currency: 'Indonesian Rupiah', ISO: 'IDR',symbol: 'Rp' },
    { currency: 'Iranian Rial', ISO: 'IRR',symbol: 'Rl' },
    { currency: 'Iraqi Dinar', ISO: 'IQD',symbol: 'ID' },
    { currency: 'Israeli New Shekel', ISO: 'ILS',symbol: '₪' },
    { currency: 'Jamaican Dollar', ISO: 'JMD',symbol: '$' },
    { currency: 'Japanese Yen', ISO: 'JPY',symbol: '¥' },
    { currency: 'Kazakhstani Tenge', ISO: 'KZT',symbol: '₸' },
    { currency: 'Kenyan Shilling', ISO: 'KES',symbol: 'KSh' },
    { currency: 'South Korean Won', ISO: 'KRW',symbol: '₩' },
    { currency: 'Kuwaiti Dinar', ISO: 'KWD',symbol: 'KD' },
    { currency: 'Kyrgyzstani Som', ISO: 'KGS',symbol: 'с' },
    { currency: 'Lao Kip', ISO: 'LAK',symbol: '₭' },
    { currency: 'Liberian Dollar', ISO: 'LRD',symbol: 'L$' },
    { currency: 'Libyan Dinar', ISO: 'LYD',symbol: 'LD' },
    { currency: 'Swiss Franc', ISO: 'CHF',symbol: 'CHF' },
    { currency: 'Malagasy Ariary', ISO: 'MGA',symbol: 'Ar' },
    { currency: 'Malawian Kwacha', ISO: 'MWK',symbol: 'K' },
    { currency: 'Japanese Yen', ISO: 'JPY',symbol: '¥' },
    { currency: 'Kazakhstani Tenge', ISO: 'KZT',symbol: '₸' },
    { currency: 'Malaysian Ringgit', ISO: 'MYR',symbol: 'RM' },
    { currency: 'Mexican Peso', ISO: 'MXN',symbol: '$' },
    { currency: 'Moldovan Leu', ISO: 'MDL',symbol: 'L' },
    { currency: 'Mauritanian Ouguiya', ISO: 'MRU',symbol: 'UM' },
    { currency: 'Mauritian Rupee', ISO: 'MUR',symbol: 'Rs' },
    { currency: 'Mongolian Tögrög', ISO: 'MNT',symbol: '₮' },
    { currency: 'Moroccan Dirham', ISO: 'MAD',symbol: 'DH' },
    { currency: 'Mozambican Metical', ISO: 'MZN',symbol: 'MT' },
    { currency: 'Myanmar Kyat', ISO: 'MMK',symbol: 'K' },
    { currency: 'CFP Franc', ISO: 'XPF',symbol: 'F' },
    { currency: 'Nicaraguan Córdoba', ISO: 'NIO',symbol: 'C$' },
    { currency: 'Nigerian Naira', ISO: 'NGN',symbol: '₦' },
    { currency: 'West African CFA Franc', ISO: 'XOF',symbol: 'F.CFA' },
    { currency: 'Macedonian Denar', ISO: 'MKD',symbol: 'den' },
    { currency: 'Turkish Lira', ISO: 'TRY',symbol: '₺' },
    { currency: 'Norwegian Krone', ISO: 'NOK',symbol: 'kr' },
    { currency: 'Pakistani Rupee', ISO: 'PKR',symbol: 'Rs' },
    { currency: 'Papua New Guinean Kina', ISO: 'PGK',symbol: 'K' },
    { currency: 'Paraguayan Guaraní', ISO: 'PYG',symbol: '₲' },
    { currency: 'Peruvian Sol', ISO: 'PEN',symbol: 'S/' },
    { currency: 'Philippine Peso', ISO: 'PHP',symbol: '₱' },
    { currency: 'Romanian Leu', ISO: 'RON',symbol: 'lei' },
    { currency: 'Rwandan Franc', ISO: 'RWF',symbol: 'FRw' },
    { currency: 'Algerian Dinar', ISO: 'DZD',symbol: 'DA' },
    { currency: 'Eastern Caribbean Dollar', ISO: 'EDC',symbol: 'EC$' },
    { currency: 'Polish Złoty', ISO: 'PLN',symbol: 'zł' },
    { currency: 'Samoan Tālā', ISO: 'WST',symbol: '$' },
    { currency: 'Serbian Dinar', ISO: 'RSD',symbol: 'DIN' },
    { currency: 'Seychellois Rupee', ISO: 'SCR',symbol: 'Rs' },
    { currency: 'Sierra Leonean Leone', ISO: 'SLE',symbol: 'Le' },
    { currency: 'Solomon Islands Dollar', ISO: 'SBD',symbol: '$' },
    { currency: 'Somali Shilling', ISO: 'SOS',symbol: 'Sh.So' },
    { currency: 'Somaliland Shilling', ISO: 'SLS',symbol: 'SI.Sh' },
    { currency: 'South Sudanese Pound', ISO: 'SSP',symbol: 'SSP' },
    { currency: 'Sri Lankan Rupee', ISO: 'LKR',symbol: 'Rs' },
    { currency: 'Sudanese Pound', ISO: 'SDG',symbol: 'LS' },
    { currency: 'Surinamese Dollar', ISO: 'SRD',symbol: '$' },
    { currency: 'Swedish Krona', ISO: 'SEK',symbol: 'kr' },
    { currency: 'Syrian Pound', ISO: 'SYP',symbol: 'LS' },
    { currency: 'New Taiwan Dollar', ISO: 'TWD',symbol: '$' },
    { currency: 'Tajikistani Somoni', ISO: 'TJS',symbol: 'SM' },
    { currency: 'Tanzanian Shilling', ISO: 'TZS',symbol: 'TSh' },
    { currency: 'Thai Baht', ISO: 'THB',symbol: '฿' },
    { currency: 'Tongan Paʻanga', ISO: 'TOP',symbol: 'T$' },
    { currency: 'Trinidad and Tobago Dollar', ISO: 'TTD',symbol: '$' },
    { currency: 'Tunisian Dinar', ISO: 'TND',symbol: 'DT' },
    { currency: 'Turkmenistani Manat', ISO: 'TMT',symbol: 'm' },
    { currency: 'Ugandan Shilling', ISO: 'UGX',symbol: 'USh' },
    { currency: 'Ukrainian Hryvnia', ISO: 'UAH',symbol: '₴' },
    { currency: 'Pound Sterling', ISO: 'GBP',symbol: '£' },
    { currency: 'Uruguayan Peso', ISO: 'UYU',symbol: '$' },
    { currency: 'Uzbekistani Sum', ISO: 'UZS',symbol: 'sum' },
    { currency: 'Vanuatu Vatu', ISO: 'VUV',symbol: 'VT' },
    { currency: 'Vietnamese Dồng', ISO: 'VND',symbol: 'đ' },
    { currency: 'Venezuelan Bolívar', ISO: 'VED',symbol: 'Bs.' },
    { currency: 'Yemeni Rial', ISO: 'YER',symbol: '﷼' },
    { currency: 'Zambian Kwacha', ISO: 'ZMW',symbol: 'K' },
    { currency: 'Real Time Gross Settlement Dollar', ISO: 'ZWL',symbol: 'RTGS$' },
]